[application]
android_main_activity = "MainActivity.kt"

[bundle]
publisher = "DioxusLabs"
identifier = "com.dioxuslabs.strake"
icon = ["./assets/strake-logo.png", "./assets/strake-logo.ico"]

[bundle.windows]
webview_install_mode = "Skip"
