
flowchart TB

    boson-paint[**boson-paint**] --> anyrender
    boson-paint --> boson-dom

    anyrender[**AnyRender**
    vello_cpu
    vello
    vello_hybrid
    skia]
    %% anyrender --> vello_cpu
    %% anyrender --> vello
    %% anyrender --> vello_hybrid
    %% anyrender --> skia

    anyrender -.-> wgpu

    %% vello --> wgpu
    %% vello_hybrid --> wgpu

    boson-html --> boson-dom

    boson-dom["`**Boson DOM**
    stylo (css)
    taffy (box layout)
    parley (text layout)
    Event handling
    Accessibility
    `"]

    %% boson-net --> boson-traits
    %% boson-html --> boson-traits
    %% boson-shell --> boson-traits
    boson-dom --> boson-traits
    boson-dom --> stylo
    boson-dom --> taffy
    boson-dom --> parley
    boson-dom --> accesskit
    %% boson-dom -.-> anyrender

    dioxus-native["`**Dioxus Native**
    `"]

    dioxus-native --> boson-paint[**boson-paint**
    AnyRender]
    dioxus-native --> boson-shell[**boson-shell**
    Winit]
    dioxus-native --> dioxus-native-dom[**dioxus-native-dom**]
    dioxus-native --> boson-net[**boson-net**
    Reqwest/Hyper]
    dioxus-native --> boson-html[**boson-html**
    html5ever]

        dioxus-native-dom --> boson-dom

    boson-shell --> boson-dom

    %% Styles

    %% style boson-paint fill:#0097B2,color:#FFFFFF
    %% style boson-html color:#FFFFFF,fill:#0097B2
    %% style boson-shell color:#FFFFFF,fill:#0097B2
    %% style boson-net color:#FFFFFF,fill:#0097B2
    %% style boson-dom fill:#0097B2,color:#FFFFFF
    %% style anyrender fill:#5CE1E6
    %% style taffy color:#000000,fill:#5CE1E6
    %% style parley fill:#5CE1E6
    %% style dioxus-native fill:#00BF63,color:#FFFFFF
    %% style dioxus-native-dom fill:#00BF63,color:#FFFFFF
    %% style stylo color:#FFFFFF,fill:#FF5757
    %% style wgpu fill:#FF5757,color:#FFFFFF
    %% style boson-traits color:#FFFFFF,fill:#0097B2
    %% style accesskit color:#FFFFFF,fill:#545454