
flowchart TB

    strake-paint[**strake-paint**] --> anyrender
    strake-paint --> strake-dom

    anyrender[**AnyRender**
    vello_cpu
    vello
    vello_hybrid
    skia]
    %% anyrender --> vello_cpu
    %% anyrender --> vello
    %% anyrender --> vello_hybrid
    %% anyrender --> skia

    anyrender -.-> wgpu

    %% vello --> wgpu
    %% vello_hybrid --> wgpu

    strake-html --> strake-dom

    strake-dom["`**Strake DOM**
    stylo (css)
    taffy (box layout)
    parley (text layout)
    Event handling
    Accessibility
    `"]

    %% strake-net --> strake-traits
    %% strake-html --> strake-traits
    %% strake-shell --> strake-traits
    strake-dom --> strake-traits
    strake-dom --> stylo
    strake-dom --> taffy
    strake-dom --> parley
    strake-dom --> accesskit
    %% strake-dom -.-> anyrender

    dioxus-native["`**Dioxus Native**
    `"]

    dioxus-native --> strake-paint[**strake-paint**
    AnyRender]
    dioxus-native --> strake-shell[**strake-shell**
    Winit]
    dioxus-native --> dioxus-native-dom[**dioxus-native-dom**]
    dioxus-native --> strake-net[**strake-net**
    Reqwest/Hyper]
    dioxus-native --> strake-html[**strake-html**
    html5ever]

        dioxus-native-dom --> strake-dom

    strake-shell --> strake-dom

    %% Styles

    %% style strake-paint fill:#0097B2,color:#FFFFFF
    %% style strake-html color:#FFFFFF,fill:#0097B2
    %% style strake-shell color:#FFFFFF,fill:#0097B2
    %% style strake-net color:#FFFFFF,fill:#0097B2
    %% style strake-dom fill:#0097B2,color:#FFFFFF
    %% style anyrender fill:#5CE1E6
    %% style taffy color:#000000,fill:#5CE1E6
    %% style parley fill:#5CE1E6
    %% style dioxus-native fill:#00BF63,color:#FFFFFF
    %% style dioxus-native-dom fill:#00BF63,color:#FFFFFF
    %% style stylo color:#FFFFFF,fill:#FF5757
    %% style wgpu fill:#FF5757,color:#FFFFFF
    %% style strake-traits color:#FFFFFF,fill:#0097B2
    %% style accesskit color:#FFFFFF,fill:#545454